name: Node.js and Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Setup Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure this file has pandas, xgboost, scikit-learn, etc.

    # Train the Model
    - name: Train Model
      run: python train_model.py

    # Calculate Dataset Quality using the Model
    - name: Calculate Dataset Quality
      run: python calculate_quality.py

    # Upload the trained model as an artifact
    - name: Save Trained Model
      uses: actions/upload-artifact@v4
      with:
        name: dataset_quality_model
        path: dataset_quality_model_xgb.pkl
